name: Shared Deploy Template

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      deploy_env:
        required: true
        type: string
    # Явно объявляем ожидаемые секреты
    secrets:
      DEV_SSH_HOST:
        required: true
      DEV_SSH_USER:
        required: true
      DEV_SSH_KEY:
        required: true
      DEV_SSH_PORT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executing ssh deploy command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script: |
            echo "Hello, World!"